import { Link } from "react-router-dom";

const CONTACT_EMAIL = "legal@experiencecaddie.com";
const LAST_UPDATED = "April 2026";

export default function Terms() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-12">
      {/* Draft notice */}
      <div className="mb-8 rounded-lg border border-amber-400 bg-amber-50 px-5 py-4 text-sm text-amber-900">
        <p className="font-semibold">⚠ DRAFT — PENDING LEGAL REVIEW</p>
        <p className="mt-1">
          This document has not been reviewed or approved by legal counsel. It is published as a
          working draft only and should not be relied upon as a final, legally binding disclosure
          or terms of use. A reviewed version will replace this draft before full public launch.
        </p>
      </div>

      <h1 className="font-serif text-3xl font-bold text-primary">Terms &amp; Affiliate Disclosure</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground">

        {/* ── Affiliate Disclosure ── */}
        <section>
          <h2 className="mb-3 font-serif text-xl font-semibold">Affiliate Disclosure</h2>
          <p className="rounded-md border border-border bg-muted/40 px-4 py-3 font-medium">
            Experience Caddie participates in affiliate programs. Some links on this site are
            affiliate links — if you click one and make a purchase or booking, we may earn a
            commission at no additional cost to you.
          </p>
          <p className="mt-4">
            Specifically, we may earn commissions through:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>
              <span className="font-medium">Ticketmaster</span> — we are enrolled in the
              Ticketmaster affiliate program. Clicks on Ticketmaster ticket links may generate a
              commission when a purchase is completed.
            </li>
            <li>
              <span className="font-medium">Booking.com via AWIN</span> — we participate in the
              AWIN affiliate network and may earn a commission on hotel bookings made through
              Booking.com links. (Integration pending full API approval.)
            </li>
            <li>
              <span className="font-medium">Other providers</span> — we may add additional
              affiliate partnerships in the future. This page will be updated to reflect any new
              relationships.
            </li>
          </ul>
          <p className="mt-4">
            <span className="font-medium">
              Our affiliate relationships do not influence what results are shown or how they are
              ordered.
            </span>{" "}
            Concerts, golf courses, and hotels are surfaced based on your destination, travel
            dates, and proximity — not by commission rate or commercial arrangement. We do not
            accept payment to feature specific providers above others.
          </p>
          <p className="mt-4">
            This disclosure is made in accordance with the United States Federal Trade Commission
            (FTC) guidelines on endorsements and testimonials (16 CFR Part 255).
          </p>
        </section>

        {/* ── Terms of Use ── */}
        <section>
          <h2 className="mb-3 font-serif text-xl font-semibold">Terms of Use</h2>

          <h3 className="mb-2 font-semibold">About the service</h3>
          <p>
            Experience Caddie is a trip-planning tool that combines publicly available concert,
            golf, and hotel data with AI-generated itinerary suggestions. It is operated by
            Fairway & Encore. By using the site, you agree to these terms.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">What we do and don't guarantee</h3>
          <p>
            We make every effort to show accurate, up-to-date information. However, concert
            availability, ticket prices, tee time availability, and hotel pricing are controlled
            by third-party providers and can change at any time. We cannot guarantee that any
            specific event, course, or hotel will be available on your selected dates.
          </p>
          <p className="mt-3">
            Itineraries generated by Experience Caddie are suggestions, not bookings. No purchase
            or reservation is made through this site. All bookings happen directly on third-party
            platforms (Ticketmaster, GolfNow, Booking.com, etc.).
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Third-party links</h3>
          <p>
            Experience Caddie links to third-party websites for ticket purchases, tee time
            bookings, and hotel reservations. We are not responsible for the content, pricing,
            availability, or policies of those third-party sites. Clicking an outbound link takes
            you off Experience Caddie and into a separate platform subject to its own terms and
            privacy policy.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Data and privacy</h3>
          <p>
            Our use of your data is described in our{" "}
            <Link to="/privacy" className="text-primary underline">
              Privacy Policy
            </Link>
            . By using the site you agree to the data practices described there.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Limitation of liability</h3>
          <p>
            Experience Caddie is provided "as is" without warranties of any kind. To the fullest
            extent permitted by law, Fairway & Encore shall not be liable for any direct,
            indirect, incidental, or consequential damages arising from your use of the service or
            any third-party services accessed through it.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Changes to these terms</h3>
          <p>
            We may update these terms as the product evolves. We will update the "last updated"
            date when we do. Continued use of Experience Caddie after an update constitutes
            acceptance of the revised terms.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Contact</h3>
          <p>
            Questions about these terms or our affiliate relationships? Email{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-12 rounded-lg border border-amber-400 bg-amber-50 px-5 py-4 text-sm text-amber-900">
        <p className="font-semibold">⚠ DRAFT — PENDING LEGAL REVIEW</p>
        <p className="mt-1">
          This document requires review by qualified legal counsel before it is treated as a
          finalised terms of use or affiliate disclosure.
        </p>
      </div>
    </div>
  );
}
