import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";

const CONTACT_EMAIL = "legal@experiencecaddie.com";
const LAST_UPDATED = "April 2026";

export default function Terms() {
  return (
    <>
      <Helmet>
        <title>Terms & Affiliate Disclosure | Experience Caddie</title>
        <meta name="description" content="Terms of service and affiliate disclosure for Experience Caddie." />
        <meta property="og:title" content="Terms & Affiliate Disclosure | Experience Caddie" />
        <meta property="og:description" content="Terms of service and affiliate disclosure for Experience Caddie." />
        <meta property="og:url" content="https://experiencecaddie.com/terms" />
        <link rel="canonical" href="https://experiencecaddie.com/terms" />
      </Helmet>
    <div className="container mx-auto max-w-3xl px-4 py-12">
      <h1 className="font-serif text-3xl font-bold text-primary">Terms &amp; Affiliate Disclosure</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground">

        {/* ── Affiliate Disclosure ── */}
        <section>
          <h2 className="mb-3 font-serif text-xl font-semibold">Affiliate Disclosure</h2>
          <p className="rounded-md border border-border bg-muted/40 px-4 py-3 font-medium">
            Experience Caddie intends to participate in affiliate programs with select providers.
            We are currently enrolled in some programs and are in the process of activating others.
            When active affiliate links are present on the site, clicking one and completing a
            purchase or booking may result in a commission to us at no additional cost to you.
          </p>
          <p className="mt-4">
            Affiliate relationships we are enrolled in or actively pursuing include:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>
              <span className="font-medium">Ticketmaster</span> — we have applied to the
              Ticketmaster affiliate program. Affiliate tracking on ticket links will be activated
              upon approval.
            </li>
            <li>
              <span className="font-medium">Booking.com via AWIN</span> — we have applied to the
              AWIN affiliate network. Hotel affiliate links will be activated upon API and program
              approval.
            </li>
            <li>
              <span className="font-medium">Other providers</span> — we may add additional
              affiliate partnerships in the future. This page will be updated whenever new
              relationships are activated.
            </li>
          </ul>
          <p className="mt-4">
            <span className="font-medium">
              Affiliate relationships — current or future — do not influence what results are shown
              or how they are ordered.
            </span>{" "}
            Concerts, golf courses, and hotels are surfaced based on your destination, travel
            dates, and proximity — not by commission rate or commercial arrangement. We do not
            accept payment to feature specific providers above others.
          </p>
          <p className="mt-4">
            This disclosure is published in accordance with the United States Federal Trade
            Commission (FTC) guidelines on endorsements and testimonials (16 CFR Part 255).
          </p>
        </section>

        {/* ── Terms of Use ── */}
        <section>
          <h2 className="mb-3 font-serif text-xl font-semibold">Terms of Use</h2>

          <h3 className="mb-2 font-semibold">About the service</h3>
          <p>
            Experience Caddie is a trip-planning tool that combines publicly available concert,
            golf, and hotel data with AI-generated itinerary suggestions. It is operated by
            Fairways & Encores. By using the site, you agree to these terms.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">What we do and don't guarantee</h3>
          <p>
            We make every effort to show accurate, up-to-date information. However, concert
            availability, ticket prices, tee time availability, and hotel pricing are controlled
            by third-party providers and can change at any time. We cannot guarantee that any
            specific event, course, or hotel will be available on your selected dates.
          </p>
          <p className="mt-3">
            Itineraries generated by Experience Caddie are suggestions, not bookings. No purchase
            or reservation is made through this site. All bookings happen directly on third-party
            platforms (Ticketmaster, GolfNow, Booking.com, etc.).
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Third-party links</h3>
          <p>
            Experience Caddie links to third-party websites for ticket purchases, tee time
            bookings, and hotel reservations. We are not responsible for the content, pricing,
            availability, or policies of those third-party sites. Clicking an outbound link takes
            you off Experience Caddie and into a separate platform subject to its own terms and
            privacy policy.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Data and privacy</h3>
          <p>
            Our use of your data is described in our{" "}
            <Link to="/privacy" className="text-primary underline">
              Privacy Policy
            </Link>
            . By using the site you agree to the data practices described there.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Limitation of liability</h3>
          <p>
            Experience Caddie is provided "as is" without warranties of any kind. To the fullest
            extent permitted by law, Fairways & Encores shall not be liable for any direct,
            indirect, incidental, or consequential damages arising from your use of the service or
            any third-party services accessed through it.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Changes to these terms</h3>
          <p>
            We may update these terms as the product evolves. We will update the "last updated"
            date when we do. Continued use of Experience Caddie after an update constitutes
            acceptance of the revised terms.
          </p>

          <h3 className="mb-2 mt-4 font-semibold">Contact</h3>
          <p>
            Questions about these terms or our affiliate relationships? Email{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </section>
      </div>
    </div>
    </>
  );
}
